### ISSUE TITLE
RGB visible images

### ISSUE THREAD

**Issue by clh-b** [hli1221/imagefusion-nestfuse#1]
How to enable fusing RGB visible images? Greys ale visible images are ok. Thanks

**Comment by hli1221** [comment]
there are two ways to fuse rgb images. 
1. expanding the channels of infrared to 3 (like rgb). then, use nestfuse to fuse each channel.
2. convert rgb to YCbCr, Y channel and infrared are fused by nestfuse. and the fused image can be generated by combine the fused Y channel and the original Cb, Cr.
