### ISSUE TITLE
作者你好，我也想问可以支持彩色图片吗？

### ISSUE THREAD

**Issue by gengyun1027** [hli1221/imagefusion-nestfuse#2]

**Comment by hli1221** [comment]
你好，感谢你对我们的工作感兴趣。
模型没有在彩色图像上训练，但是依然可以融合彩色图像。有两种方式，
1. 将rgb图像的三个通道分别和infrared图像的三个通道分别用此方法融合，得到三个融合后的通道信息，最终输出彩色图像。
2. 将rgb图像转换到YCbCr颜色空间，Y通道和infrared的灰度图融合，最后用融合后的Y通道加上原来的Cb和Cr通道信息，最终输出彩色图像。

**Comment by gengyun1027** [comment]
> 你好，感谢你对我们的工作感兴趣。 模型没有在彩色图像上训练，但是依然可以融合彩色图像。有两种方式，
> 
> 1. 将rgb图像的三个通道分别和infrared图像的三个通道分别用此方法融合，得到三个融合后的通道信息，最终输出彩色图像。
> 2. 将rgb图像转换到YCbCr颜色空间，Y通道和infrared的灰度图融合，最后用融合后的Y通道加上原来的Cb和Cr通道信息，最终输出彩色图像。

好的，谢谢您的回复
