### ISSUE TITLE
请问作者test时为什么大于512的尺寸的要这样切开呢？

### ISSUE THREAD

**Issue by linklist2** [hli1221/imagefusion-nestfuse#3]
![image](https://user-images.githubusercontent.com/46252413/176981890-e431f08f-81ef-41ce-95e3-19bbd9e2ba1d.png)

**Comment by hli1221** [comment]
你好，由于网络模型的设置以及显存的限制（Titan Xp 12G），如果输入图像过大会导致显存不足，且运行速度变慢。
为了优化测试过程，因此将尺寸大于512的图片进行分块处理，在最后进行拼接。

**Comment by hli1221** [comment]
理论上显存足够也可以不做分块，但是在测试的时候占用过多显存也不太合理。

**Comment by linklist2** [comment]
@hli1221 好的，非常感谢您的解答。
